global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pmetrics'
    static_configs:
      - targets: ['exporter:9187']
        labels:
          instance: 'pmetrics-demo'
